URL: 'http://47.96.31.154:26000'


PARAMS:
  clientType: android
  appVersion: 3.3.0
  deviceId: 864553033145254
  mobilePhone: 17621717316
  deviceName: OPPO%20R11
  osVersion: 7.1.1
  appName: jsxjx
  packageId: com.innext.xjx
  appMarket: xjx-MySelf
  merchantNumber: cjxjx
  username: 17621717316
  password: a123456


login_url: '/credit-user/login'


index_url: '/credit-app/index'

risk_url: '/refactor/risk/riskTokenSend'




