URL: 'http://prod-super.xianjinxia.com'

PARAMS:
  clientType: android
  appVersion: 3.3.0
  deviceId: 864553033145254
  mobilePhone: 17621717316
  deviceName: OPPO%20R11
  osVersion: 7.1.1
  appName: jsxjx
  packageId: com.innext.xjx
  appMarket: xjx-MySelf
  merchantNumber: cjxjx